### Fields of Mathematics for Deep Learning
1. Linear Algebra
2. Statistics
3. Calculus

## Four Steps of a Deep Learning Pipeline
1. Collect Data
2. Build Model
3. Train Model
4. Test Model

---

*Compare this with...*

#### The Systematic Process For Working Through Predictive Modeling Problems
*That delivers above average results* ([Source](http://machinelearningmastery.com/process-for-working-through-machine-learning-problems/))
1. Define the Problem
2. Prepare the Data
3. Spot Check Algorithms
4. Improve Results
5. Present Results

There's much here that be mapped to the previous process.
- I leave you to realize it

---

### Data Preparation
1. Clean Data
  - Drop empty values
  - Remove unnecessary features
2. Normalizing data
  - Helps the model reach convergence by causing all neurons in the network to operate on the same scale
  - Working in the same scale (or 'range') definitively gives nodes/neurons less to choose from, increasing probabilities for more appropriate values by default
3. Adapt Data
  - Insure the data is in a format the network will accept

---
Vocabulary:
  - **Convergence (point)**. The point where error of the prediction function approaches its asymptotic minimum.
  - **Feature**. A dimension of some observed occurence (aka 'data').
    - Examples: brain weight of an animal, height of a human, horse power of a car
  - **Adapt**. To translate, massage, trim, or otherwise re-package your data for consumption.

---

#### Normalization via 'min-max' scaling
Given:
- Some domain, X
- Some element of X, x
- A pair of functions, `max` and `min`

The equation will normalize an `x` relative to its neighbors
- This is vaguely familiar.
  - The equations for correlation of data (to the line of best fit) use something like this process.
  - Because each data point has a distance to the LoBF, you need a similar scaling to find that "distance"
    - The closer a point to the LoBF, the higher the correlation.

\begin{equation*}
z = \frac{x - min(X)}{max(X) - min(X)}
\end{equation*}

#### Adapting Data

Quick jump to Linear Algebra
- Some terms that are brought up a **lot**
  1. Scalars - single number
  2. Vector - multiple numbers in one dimension
    - Funnily enough, vectors signify dimensionality in multi-variable (Newtonian) Calculus and any Physics class.
  3. Matrix - Multiple numbers in two dimensions
  4. Tensor - Numbers in *n* dimensions

Simple ideas can have complex or simple explanations
- For example: 1 is a "number". Clearly.
  - But we also call it an "integer" and a "real" number (not on the imaginary plane).
  - It can even be a "floating point" number, with no value after the decimal point to represent.
- From this, we can conclude that more *rudamentary* ideas can be encapsulated in more *exceptional* forms of categorization.

**This is why** we use *Tensors*: because the other three categories can **all** be represented as a Tensor.

---
***In other words***
Tensors: N-Dimensional Matrices
- 0-Dimensional --> Scalar
- 1-Dimensional --> Vector
- 2-Dimensional --> Matrix

---

We'll now start to place with a neural network.

...
Some list that Siraj is putting out (in a really crappy song)...

Looks to be "How a Neural Network works", or something to that effect.

1. Normalize
2. Learning Hyperparameters
3. Initializing Weights
4. Forward Propogation
5. Calculate Error
6. Back propogate
  - Rebalance weights

In [4]:
import numpy as np

In [5]:
# Collect Data
x = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1]
])
y = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [6]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [7]:
print(y)

[[0]
 [1]
 [1]
 [0]]


---
Vocabulary:
  - **Hyperparameters**. High-level tunings of the network itself. Changes the resultant neural network in such ways as:
    - Learning rate
    - How many hidden layers
    - ***Please note***: these will be increasingly important as the network grows in size.

## Conclusion

The next two minutes (from 4:00 to ~6:30) are unfairly fast. He's skipping the math and just putting numbers up, which is not helpful.
- On the plus side, he gave a great intuitive explanation of *Gradient Descent*...

**Gradient Descent**
Roughly: an iterative process of approximation (very much like Calculus derivatives), for the purpose of reaching a 0-slope ("no slope") in our graph, thus minimizing error.
- I say "thus" because a positive slope is a positive error and negative slope a negative error
  - Only at no-slope is there no error.
- **We use this** to find a sense of direction in calculating error of predictions (as explained above) in **modifying our weights**
  - Thus shorting the iterations the network must take to complete the job

... Also, the **gradient** is a the **slope at a *point***.

---
It's been an hour (it is now 12:52 AM) since I started this notebook.

Thankfully, Siraj made a ["How to Make a Neural Network"](https://www.youtube.com/watch?v=p69khggr1Jo&index=3&list=PL2-dafEMk2A7YdKv4XfKpfbTH5z6rEEj3)

Further proof that this course isn't perfect: "Intro to Neural Networks" is two lessons away. If it's an hour-per-lesson, I'll be caught up in no time.

If not... Well, I'm gonna rock it and get this first project done.

---
### Thankfully

[Deep Learning Book](http://www.deeplearningbook.org/contents/intro.html) exists!
- The intro maps out how to read the book
  - It even says that it's meant to get developers up to speed, so they can have a machine learning and AI centric career
  - This is a segment of my exact goal.

And if I get to a good place, there is [a challenge to build a neural network](https://github.com/llSourcell/how_to_do_math_for_deep_learning) that I hope will bolster my capabilities.

Lastly, for becoming a Data Scientist, I'm hopeful that the following posts will prove insightful and not condescendent or redundant
- [ML for Programmers](http://machinelearningmastery.com/machine-learning-for-programmers/)
- [ML Mastery Method](http://machinelearningmastery.com/machine-learning-mastery-method/)

---
Then again, I probably don't need them at all. I've got a rhythm going and I don't need to keep looking at myself like an __absolute__ beginner.
- Much like I treat myself with foreign languages.
- The guard-rail is nice, but I've out grown the training wheels.