It would seem that all the fly-by content will have its source materials expounded upon...

This is a very good thing.

---

2016년 4월 16일

**오후 4시 26분**

Here's what I know (and believe) about NumPy:
- It's a general purpose mathematics library
- There are a plethora of functions and utilities around matrix calculations
  - because everything can be respresented as a matrix/tensor
  - This is actually **really** good for advancing my Mathematic skills
    - Lots of higher maths are done with Matrices
- There are immutable data structures
  - Helps with speed
- Big in the Data Analysis/Data Science/Big Data communities, because it makes doing the big math really simple.
  - Sometimes, one library is just the fastest way to do something
  - Less of a chore to do the math we all (fundamentally) understand

... And that's about it.

---
Took about 10 minutes to investigate the purchase of a Galaxy S8

---
**오후 4시 50분**

# Data has Dimensions
> Before we can start designing Neural Networks ourselves, we first need to understand how we represent that data
More specifically, we need to think about the shapes that data can have

Consider a person...

- We could represent that person's height in centimeters as a *single* number.
- Or we could have a list of numbers, representing the various features of that person
  - Height, weight and age
- Maybe we have an image of the person
  - A grid of rows and columns
  - Possibly represent those grid cells as a RGB (vector) of the color shown.

Look at the depth of that data! All of which are described in dimensions.

Once again, going through the dimensions:

### Scalars
Zero-dimensional shape.
- A person's height is a *really* good example of this

> It's kind of impossible to picture zero dimensions, but that's how it is most accurately defined.

### Vectors
Lists of values.

They come in two types: Row (horizontal) and Column (verticle)
- Note that they can store the same data, it's just the math at your disposal that changes

They have **one dimension**: length.

> We could store a person's height, weight, and age all as a vector

### Matrices
Two-Dimensional grid of values

\begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{vmatrix}

> We see that this has two **rows** and three **columns**, so we'll call this a "two-by-three" matrix
- Notated: `2 x 3`

If you had a single number for each pixel of an image ("Bitmap \*cough cough\*), you could store those as a matrix :)

### Tensors
N-Dimensional collection of values
- Garrett found a brilliant way to visualize data in 13 dimensions

The aforementioned Scalar, Vector, and Matrix groups are \_-dimension of tensor
- Scalar is a 0-D Tensor
- Vector is a 1-D Tensor
- Matrix is a 2-D Tensor

Higher dimensional data is tough to visualize. For example:
- For three dimensions, one might picture
  - A stack of matrices (i.e. stack of punch cards for a program)
  - A list of matrices (i.e. lens of a pair of glasses. Or [techie] a sequence of filters)
  - A matrix of vectors (i.e. an array-of-arrays.)
    - Easiest to get into code in most C-family languages

Sounds like fun, doesn't it? :D

What about 4-D?
- We could have a matrix of matrices, because `2 x 2 = 4` dimensions
- Or it could be a list of lists or stack of stacks of matrices
  - Again, the compounding here

***The point is***:
> Even if you have a hard time imagining how the data is arranged, you can probably still make the math work.

---
Back to an image, with RGB channels.
- Would could store that data three-dimensionally
  - A stack of matrices: one for each color channel

For these lessons...
- We'll mostly consider [Scalars](./Topic%202%20-%20Matrix%20Math%20and%20Numpy.ipynb#Scalars) and [Matrices](./Topic%202%20-%20Matrix%20Math%20and%20Numpy.ipynb#Matrices)
  - Vectors will just be a Matrix, where one of their dimensions is `1`

Values will be referenced by their two-dimensional indices $lowerCaseMatrixName_{<row><column>}$

$$
\begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix}
\begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}
$$
- Therefore, value `8` is index `32` in linear algebra

# Working with Data in NumPy

---
The [NumPy Reference Documentation](https://docs.scipy.org/doc/numpy/reference/)
- Was actually written in C, so that is can be more performant that Python
  - This is a perfectly legitimate reason to lean on a library for something.
  - I'm pleased to know that it's not due to laziness in implementation
- Most work is indeed done through matrices, as [`ndarray`](https://docs.scipy.org/doc/numpy/reference/arrays.html) instances

---

## NumPy Data Types
That we'll be using.
It's the Big Four, as previously mentioned (in Siraj's video)

### NumPy Scalars
- Created with `numpy.array`, and you pass a number (Python int or float)
- Can be of type `int` or `uint` 8-64

In [1]:
import numpy as np

In [2]:
scal = np.array(5)

In [3]:
print(scal)

5


- Exposes the relevant property `shape`

In [4]:
print(scal.shape)

()


- Returns an empty tuple, representing its **0-D nature**
  - Coming full circle
- Can still do basic operations (`+`, `*`, etc.) against other Python types.

In [5]:
print(scal + 10)

15


### NumPy Vectors and Matrices
- All that was true about Scalars maps to these as well

In [6]:
vect = np.array([1, 2, 3, 4])

- Also support slices (i.e. `arr[1:]`)
  - See [the documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) for more, but it's pretty straightforward

In [7]:
print(vect)

[1 2 3 4]


In [8]:
print(vect.shape)

(4,)


In [9]:
print(vect[2:])

[3 4]


#### NumPy Matrices
- As stated, we'll do this programmatically as an array-of-arrays

In [10]:
matrx = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
matrx.shape

(3, 3)

In [12]:
matrx[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [13]:
matrx[1:][0]

array([4, 5, 6])

In [14]:
# Give us an array of our last-row-array, and print the last element
matrx[2:][0][-1]

9

### That's really nice, but...

In [15]:
# what if we need a different shape to the data?
# Recall our vector
vect

array([1, 2, 3, 4])

In [16]:
vect.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [17]:
vect

array([1, 2, 3, 4])

In [18]:
vect.reshape((1,4))

array([[1, 2, 3, 4]])

So we can give our data extra dimensionality if needed
> But we can go deeper, and follow the experts in the community

In [19]:
vect[None, :] # NumPy, can you give me a new dimension of size '1' for Y-axis?

array([[1, 2, 3, 4]])

In [20]:
vect[:, None] # How about that X-axis, while we're at it?

array([[1],
       [2],
       [3],
       [4]])

**This reshaping logic** is a lot less literal, and will work on more general data
- May not be the thing we want every time, but it's very popular to use this technique

---
I'm suspecting that I won't write a lot for the upcoming sections, so I'm just going to grab loose thoughts and organize them afterwards (ergo "oh this was all stuff about matrix multiplication...")

- Scalar (+,-,\*,/) matrix performs the operation against every element of the scalar to produce a result

In [21]:
2 * vect

array([2, 4, 6, 8])

- Thinking back to an RGB tensor, we could **normalize** our channels by dividing the matrix by 255
  - 256 points including 0, but we try not to divide by zero ;)
- What if we made every element of our matrix a fraction, instead?

In [22]:
from fractions import Fraction

In [23]:
list(map(lambda x: Fraction(x, 8), vect)) # deal with all the data in terms of 8ths

[Fraction(1, 8), Fraction(1, 4), Fraction(3, 8), Fraction(1, 2)]

- Matrix element-wise math (i.e. addition and subtraction) requires matching dimensions

In [24]:
other_vect = np.array([6, 7, 8, 9])
vect + other_vect

array([ 7,  9, 11, 13])

In [25]:
other_vect - vect

array([5, 5, 5, 5])

---
오후7시부터 8시35분까지 쉬었다.
***

# Matrix Multiplication
***A.k.a. the ["dot product"](https://en.wikipedia.org/wiki/Dot_product)***
- Which is a process for converting two vectors (of equal length) into a single scalar

So how does this help us???

#### Dot Product: Row by Column

When we find the dot-product of two matrices, we're just finding the dot-product of **rows of the first matrix** against the **columns of the second matrix**
- Given matrix A, (2 x 4), and matrix B (4 x 3), the resultant matrix will be of (2 x 3)
  - The "inner" (2 x __4__) * (__4__ x 3) dimensions must match
  - And the result is of the "outer" (__2__ x 4) * (4 x __3__) or (2 x 3)

__THIS IS IMPORTANT__ and will be elaborated upon in a later lesson.
- Instructor does a walk through of matrix dot-product
  - Dot products are a fair bit of computation, given the size of the result.
- Take our (2 x 4) and (4 x 3), resulting in a (2 x 3) example:
  - 6 (again, 2\*3) numbers are the result of
    - 24 Multiplication operations, and
    - 18 Addition operations

---
Video two is just covering the things I already know about Linear Algebra.

The __only point__ I left out (explicitly): order matters. Pretty easy progress, for low cost (just double checking the video at 1.25x speed ;)

---

## NumPy Matrix Multiplication
Two functions to know
1. [`np.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)
  - Don't forget its cousin [np.tensordot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tensordot.html#numpy.tensordot)
2. [`np.matmul`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)
  - Short for __mat__rix __mul__tiplication

---
Small detour to understand some of the code from the documentation

In [30]:
vect.dot(other_vect[:, None])

array([80])

In [35]:
some_matrix = np.arange(3*2*5).reshape((3,5,2))

In [36]:
some_matrix.shape

(3, 5, 2)

In [37]:
some_matrix

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [42]:
# I wanted something that would allow me to test this multi-indexing syntax
some_matrix[1,1,0]

12

In [51]:
# And this one. It looks like the "gallop", but I'm not sure at this level...
some_matrix[::-1] # actually, it does reverse the stack of lists

array([[[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]]])

In [52]:
# reversing two levels of depth
some_matrix[::-1, ::-1] # first the stacks, then the lists themselves

array([[[28, 29],
        [26, 27],
        [24, 25],
        [22, 23],
        [20, 21]],

       [[18, 19],
        [16, 17],
        [14, 15],
        [12, 13],
        [10, 11]],

       [[ 8,  9],
        [ 6,  7],
        [ 4,  5],
        [ 2,  3],
        [ 0,  1]]])

In [ ]:
reversed_view = some_matrix[::-1, ::-1]

__So__ let's take a dot product of a (2 x 4) and a (4 x 2)!

In [57]:
reversed_view[1].T # I know about this because I read.

array([[18, 16, 14, 12, 10],
       [19, 17, 15, 13, 11]])

In [58]:
some_matrix[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
reversed_view[1].T.dot(some_matrix[0])

array([[240, 310],
       [260, 335]])

***For the record***: we should use `matmul` for basically everything that isn't 2-D, because the rules change (slightly) and we won't be able to rely on it as readily.

In [61]:
np.matmul(reversed_view[1].T, some_matrix[0])

array([[240, 310],
       [260, 335]])

---

#### An idea
Doing a transpose on a matrix would be a fast way to flip data, so writing to my matrices doesn't have to be wierd
- It's probably poor form, but I am the guy who abstracted away 0-based indexing...

Could also rearrange the order, so that the "inner" and "outer" pair are swapped...
- Just food for thought

---
Resuming watching videos...

---

__The instructor__ makes a good point in data representation
- If the rows represent a person and columns respresent a feature (i.e. height), then the transpose flips this
  - It could be a hairy situation really quickly.
- He just noted the "idea" I just stated.
  - I'm a step ahead of this video ;)
  - Showing a lot of ways to make the math work

### When to break the rules
> We've shown we can make the math work.
- Now let's show we it __is__ and __isn't__ a good idea

Let's take two example matrices (call them "A" and "B")

\begin{align}
\begin{vmatrix}
1 & 3 \\
5 & 7 \\
9 & 11
\end{vmatrix}
\begin{vmatrix}
0  & 2 \\
4  & 6 \\
8  & 10 \\
12 & 14
\end{vmatrix}
\end{align}

#### If both matrices are arranged in rows
Either way is fine
- Transpose B with matrix product for a resultant (3 x 4)
- Swap positions, then transpose A for a resultant (4 x 3)
  - Both results __are actually transposes__ of one another

#### If both are arranged as columns
__Neither__ option works, because we can't get features/persons (if we're using our old example)
> Each dot product taken ends of combining values from every data item, rather than elements of related items (like we probably intended).

#### What about other permutations?
__Nope__.
- Trying will just be an exercise in frustration.
> You can safely use a transpose ina matrix multiplication IFF the data in both of your original matrices are arranged as rows
- Be that __rows of *features*__ (i.e. *height* of a person), or __rows of '*owners of features*'__ (i.e. *person* "owning" their height)

### Does this outlaw data as columns?
Heck no!
- Store data as it makes sense!
  - Only transpose when you have to!
- If you properly adapted your data, a lot of this problem goes away
  - But, still, some things are unavoidable

### A real-world use case
Let's say we're making a Neural Network (I wonder why we would do that?)
- We've got some `inputs` and `weights`

In [63]:
# notice this is really a vector, but it's in matrix form
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [64]:
inputs.shape

(1, 4)

In [66]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [67]:
weights.shape

(3, 4)

__We can't__ immediately take the matrix product, because we have mismatched dimensions
- The "arranged by rows" strategy works like a charm here.

In [68]:
weights.dot(inputs.T) # same as np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

In [69]:
inputs.dot(weights.T) # same as np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

__Since these are just__ transposes of one another...
> It really just depends on the shape you want for your output.

Ergo, make a choice and go!

### Quiz Time!!!
오후 9시 53분 (~1시 20분후에...)

The quiz is a library tour of NumPy, in a nutshell
- Exposure to:
  - [ndarray.min](https://docs.scipy.org/doc/numpy/reference/generated/numpy.amin.html#numpy.amin), [ndarray.max](https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html#numpy.amax), [ndarray.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html#numpy.mean)
  - Which (I think) really just alias
    - [np.minimum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.minimum.html#numpy.minimum)
    - [np.maximum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html#numpy.maximum)

In [73]:
# Here's a decent test function
def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose

    if (not (m1.shape[1] == m2.shape[0] or m1.shape[0] == m2.shape[1])):
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if (m1.shape[1] == m2.shape[0]):
        return m1.dot(m2)
    if (m1.shape[0] == m2.shape[1]):
        return m2.dot(m1)

# Next Stop: Intro to Neural Networks
__오후 10시 25분 끝났다__