It would seem that all the fly-by content will have its source materials expounded upon...

This is a very good thing.

---

2016년 4월 16일

**오후 4시 26분**

Here's what I know (and believe) about NumPy:
- It's a general purpose mathematics library
- There are a plethora of functions and utilities around matrix calculations
  - because everything can be respresented as a matrix/tensor
  - This is actually **really** good for advancing my Mathematic skills
    - Lots of higher maths are done with Matrices
- There are immutable data structures
  - Helps with speed
- Big in the Data Analysis/Data Science/Big Data communities, because it makes doing the big math really simple.
  - Sometimes, one library is just the fastest way to do something
  - Less of a chore to do the math we all (fundamentally) understand

... And that's about it.

---
Took about 10 minutes to investigate the purchase of a Galaxy S8

---
**오후 4시 50분**

# Data has Dimensions
> Before we can start designing Neural Networks ourselves, we first need to understand how we represent that data
More specifically, we need to think about the shapes that data can have

Consider a person...

- We could represent that person's height in centimeters as a *single* number.
- Or we could have a list of numbers, representing the various features of that person
  - Height, weight and age
- Maybe we have an image of the person
  - A grid of rows and columns
  - Possibly represent those grid cells as a RGB (vector) of the color shown.

Look at the depth of that data! All of which are described in dimensions.

Once again, going through the dimensions:

### Scalars
Zero-dimensional shape.
- A person's height is a *really* good example of this

> It's kind of impossible to picture zero dimensions, but that's how it is most accurately defined.

### Vectors
Lists of values.

They come in two types: Row (horizontal) and Column (verticle)
- Note that they can store the same data, it's just the math at your disposal that changes

They have **one dimension**: length.

> We could store a person's height, weight, and age all as a vector

### Matrices
Two-Dimensional grid of values

\begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{vmatrix}

> We see that this has two **rows** and three **columns**, so we'll call this a "two-by-three" matrix
- Notated: `2 x 3`

If you had a single number for each pixel of an image ("Bitmap \*cough cough\*), you could store those as a matrix :)

### Tensors
N-Dimensional collection of values
- Garrett found a brilliant way to visualize data in 13 dimensions

The aforementioned Scalar, Vector, and Matrix groups are \_-dimension of tensor
- Scalar is a 0-D Tensor
- Vector is a 1-D Tensor
- Matrix is a 2-D Tensor

Higher dimensional data is tough to visualize. For example:
- For three dimensions, one might picture
  - A stack of matrices (i.e. stack of punch cards for a program)
  - A list of matrices (i.e. lens of a pair of glasses. Or [techie] a sequence of filters)
  - A matrix of vectors (i.e. an array-of-arrays.)
    - Easiest to get into code in most C-family languages

Sounds like fun, doesn't it? :D

What about 4-D?
- We could have a matrix of matrices, because `2 x 2 = 4` dimensions
- Or it could be a list of lists or stack of stacks of matrices
  - Again, the compounding here

***The point is***:
> Even if you have a hard time imagining how the data is arranged, you can probably still make the math work.

---
Back to an image, with RGB channels.
- Would could store that data three-dimensionally
  - A stack of matrices: one for each color channel

For these lessons...
- We'll mostly consider [Scalars](./Topic%202%20-%20Matrix%20Math%20and%20Numpy.ipynb#Scalars) and [Matrices](./Topic%202%20-%20Matrix%20Math%20and%20Numpy.ipynb#Matrices)
  - Vectors will just be a Matrix, where one of their dimensions is `1`

Values will be referenced by their two-dimensional indices $lowerCaseMatrixName_{<row><column>}$

$$
\begin{vmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{vmatrix}
\begin{vmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{vmatrix}
$$
- Therefore, value `8` is index `32` in linear algebra

# Working with Data in NumPy

---
The [NumPy Reference Documentation](https://docs.scipy.org/doc/numpy/reference/)
- Was actually written in C, so that is can be more performant that Python
  - This is a perfectly legitimate reason to lean on a library for something.
  - I'm pleased to know that it's not due to laziness in implementation
- Most work is indeed done through matrices, as [`ndarray`](https://docs.scipy.org/doc/numpy/reference/arrays.html) instances

---

## NumPy Data Types
That we'll be using.
It's the Big Four, as previously mentioned (in Siraj's video)

### NumPy Scalars
- Created with `numpy.array`, and you pass a number (Python int or float)
- Can be of type `int` or `uint` 8-64

In [18]:
import numpy as np

In [19]:
scal = np.array(5)

In [20]:
print(scal)

5


- Exposes the relevant property `shape`

In [21]:
print(scal.shape)

()


- Returns an empty tuple, representing its **0-D nature**
  - Coming full circle
- Can still do basic operations (`+`, `*`, etc.) against other Python types.

In [22]:
print(scal + 10)

15


### NumPy Vectors and Matrices
- All that was true about Scalars maps to these as well

In [23]:
vect = np.array([1, 2, 3, 4])

- Also support slices (i.e. `arr[1:]`)
  - See [the documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) for more, but it's pretty straightforward

In [24]:
print(vect)

[1 2 3 4]


In [25]:
print(vect.shape)

(4,)


In [26]:
print(vect[2:])

[3 4]


#### NumPy Matrices
- As stated, we'll do this programmatically as an array-of-arrays

In [27]:
matrx = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
matrx.shape

(3, 3)

In [35]:
matrx[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
matrx[1:][0]

array([4, 5, 6])

In [37]:
# Give us an array of our last-row-array, and print the last element
matrx[2:][0][-1]

9

### That's really nice, but...

In [33]:
# what if we need a different shape to the data?
# Recall our vector
vect

array([1, 2, 3, 4])

In [38]:
vect.reshape((4, 1))

array([[1],
       [2],
       [3],
       [4]])

In [39]:
vect

array([1, 2, 3, 4])

In [40]:
vect.reshape((1,4))

array([[1, 2, 3, 4]])

So we can give our data extra dimensionality if needed
> But we can go deeper, and follow the experts in the community

In [41]:
vect[None, :] # NumPy, can you give me a new dimension of size '1' for Y-axis?

array([[1, 2, 3, 4]])

In [42]:
vect[:, None] # How about that X-axis, while we're at it?

array([[1],
       [2],
       [3],
       [4]])

**This reshaping logic** is a lot less literal, and will work on more general data
- May not be the thing we want every time, but it's very popular to use this technique

---
I'm suspecting that I won't write a lot for the upcoming sections, so I'm just going to grab loose thoughts and organize them afterwards (ergo "oh this was all stuff about matrix multiplication...")

- Scalar (+,-,\*,/) matrix performs the operation against every element of the scalar to produce a result

In [43]:
2 * vect

array([2, 4, 6, 8])

- Thinking back to an RGB tensor, we could **normalize** our channels by dividing the matrix by 255
  - 256 points including 0, but we try not to divide by zero ;)
- What if we made every element of our matrix a fraction, instead?

In [45]:
from fractions import Fraction

In [47]:
list(map(lambda x: Fraction(x, 8), vect)) # deal with all the data in terms of 8ths

[Fraction(1, 8), Fraction(1, 4), Fraction(3, 8), Fraction(1, 2)]

- Matrix element-wise math (i.e. addition and subtraction) requires matching dimensions

In [48]:
other_vect = np.array([6, 7, 8, 9])
vect + other_vect

array([ 7,  9, 11, 13])

In [49]:
other_vect - vect

array([5, 5, 5, 5])